### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gfiehler** [volbrene/redoc#1]
Hi I work for a company that would like to use this software, we are happy with its management of multiple files which has been a problem we have been looking to solve for a while.  Would you consider adding a license file so that we could understand what ability we have to use, modify, etc.   I have taken the code and changed images files for our branding and would like to remove your name from the lower right corner, but would maintain copyright info in your code, but we have not deployed this software due to lack of licensing.
I have used this link to help me review licenses in the past https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license .  personally I try to use mit or apache 2.0 but that is your call.  Without a license file, according to the link no one has any rights to use this code.

Thanks
Gregg

**Comment by volbrene** [comment]
Thanks a lot for your issue and the hint for the missing license. I added the MIT license because I want to strengthen the community. I am happy that I can help others with my solution. Have fun with the project.
