### ISSUE TITLE
Redoc left menu broke with Chrome 80

### ISSUE THREAD

**Issue by gfiehler** [volbrene/redoc#2]
Hi, found out yesterday that Chrome 80 release broke the left menus in Redoc, they have fixed the issue but I had to update your package.json locally to use 

 "redoc": "^2.0.0-rc.23",

and then npm install to rebuild the package-lock.json and npm run build to get a new build.

I'm working fine on my side but wanted to let you know.
BTW everyone loves the viewer so we thank you for open sourcing it.
Thanks
Gregg

**Comment by volbrene** [comment]
Many thanks for the advice. I am happy if I can help others with the project here.

A Docker image update is under construction.
