### ISSUE TITLE
Adding local files and exposing them

### ISSUE THREAD

**Issue by harsh4870** [volbrene/redoc#3]
Hi..! Thanks a lot for creating open-source amazing project. i have tried it's awesome however i am trying to customize it as per need and facing some issue if you help with it.

i have created docker images like 

```
FROM volbrene/redoc
COPY . /usr/share/nginx/html/
```
Adding my local yaml files inside docker image and running docker image like

`docker run -p 80:80 -e URLS="[{url: '/instagram.yaml', name: 'insta-service'}, {url: '/petstore.yaml', name: 'Petshop'}, {url: '/test-service/swagger.yaml', name: 'account-service'}]" redoc-test-1`

i have tried the same swagger-ui it's working well by adding local files at path `/usr/share/nginx/html/` i have tried here but it giving error. 

i have used same YAML used in

` docker run -d     -p 80:80     -e URLS="[{url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petshop'},{url: 'https://api.apis.guru/v2/specs/instagram.com/1.0.0/swagger.yaml', name: 'Instagram'}]"      volbrene/redoc`

Can you help here i want to add files in docker images and expose UI then.

Thanks...!

**Comment by volbrene** [comment]
Hey, I have updated the readme of this project. The readme should now describe the solution to your problem.
I hope I could help.
